name: "Library: Init"

on:
  workflow_call:
    inputs:
      checkout_ref:
        required: false
        type: string
        default: ""

permissions: write-all

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    env:
      DOCKERFILE_PATH: ./docker/Dockerfile
      BUILD_CONTEXT: ./docker
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0
          ref: ${{ inputs.checkout_ref || github.sha }}

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.1

      - name: Hadolint
        id: hadolint
        uses: hadolint/hadolint-action@v3.3.0
        with:
          dockerfile: ${{ env.DOCKERFILE_PATH }}

      - name: Shellcheck
        id: shellcheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          severity: error
          scandir: ./docker/bin
          ignore_paths: ".git"

      - name: Helm lint
        id: helm_lint
        run: bash ./.github/workflows/scripts/library-init.sh helm-lint

      - name: Render Helm templates
        id: helm_template
        run: bash ./.github/workflows/scripts/library-init.sh render-helm

      - name: Kubeconform
        id: kubeconform
        run: bash ./.github/workflows/scripts/library-init.sh kubeconform
